"🚀 Features":
  - head-branch:
      - '^feature/.*'

"🐛 Bug Fixes":
  - head-branch:
      - '^fix/.*'
      - '^hotfix/.*'

"📚 Documentation":
  - head-branch:
      - '^docs/.*'

"🧹 Chores":
  - head-branch:
      - '^chore/.*'
