# .github/labeler.yml

'🚀 Features':
  - head-branch:
      - 'feature/*'

'🐛 Bug Fixes':
  - head-branch:
      - 'fix/*'
      - 'hotfix/*'

'📚 Documentation':
  - head-branch:
      - 'docs/*'

'🧹 Chores':
  - head-branch:
      - 'chore/*'

'🧪 Tests':
  # 브랜치명 패턴
  - head-branch:
      - 'test/*'
  # 테스트 파일 변경 감지
  - changed-files:
      any-glob-to-any-file:
        - '**/*.spec.ts'
        - '**/*.test.ts'
        - 'test/**'

'🤖 deploy':
  - changed-files:
      any-glob-to-any-file:
        - '.github/workflows/**'
        - 'ci/**'
        - 'Dockerfile*'
        - '*.yml'
        - '.aws/**'
