# .github/labeler.yml

"🚀 Features":
  head-branch:
    - '^feature/.*'

"🐛 Bug Fixes":
  head-branch:
    - '^fix/.*'

"📚 Documentation":
  head-branch:
    - '^docs/.*'

"⚡ Performance":
  head-branch:
    - '^perf/.*'

"🔒 Security":
  head-branch:
    - '^security/.*'

"🧹 Chores":
  head-branch:
    - '^chore/.*'

"🔀 Other Changes":
  head-branch:
    - '^release/.*'
