# .github/labeler.yml
"🚀 Features":
  head-branch:
    - feature/*

"🐛 Bug Fixes":
  head-branch:
    - fix/*
    - hotfix/*

"📚 Documentation":
  head-branch:
    - docs/*

"🧹 Chores":
  head-branch:
    - chore/*

"🧪 Tests":
  head-branch:
    - test/*
  paths:
    - '**/*.spec.ts'
    - '**/*.test.ts'
    - 'test/**'

"🤖 deploy":
  paths:
    - .github/workflows/**
    - ci/**
    - Dockerfile*
    - '*.yml'
    - .aws/**
