"🚀 Features":
  - head-branch: ['^feature/*', 'feature/*']

"🐛 Bug Fixes":
  - head-branch: ['^fix/*', 'fix/*', '^hotfix/*', 'hotfix/*']

"📚 Documentation":
  - head-branch: ['^docs/*', 'docs/*']

"🧹 Chores":
  - head-branch: ['^chore/*', 'chore/*']
