# .github/labeler.yml
'🚀 Features':
  head-branch:
    - 'feature/*'       # feature/~~ 에서만

'🐛 Bug Fixes':
  head-branch:
    - 'fix/*'
    - 'hotfix/*'

'📚 Documentation':
  head-branch:
    - 'docs/*'

'🧹 Chores':
  head-branch:
    - 'chore/*'

'🧪 Tests':
  paths:
    - 'test/**'
    - '**/*.spec.ts'
    - '**/*.test.ts'

'🤖 deploy':
  paths:
    - '.github/workflows/**'
    - 'ci/**'
    - 'Dockerfile*'
    - '*.yml'
    - '.aws/**'
