# .github/release.yml

# 1) 릴리즈 제목·태그 포맷
name-template: '릴리즈 v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

# 2) Draft Release 본문 템플릿
template: |
  ### 📱 Android 빌드 버전
  <!-- ex) 12345 -->

  ### 🍎 iOS 빌드 버전
  <!-- ex) 67890 -->

  ### 🔄 변경사항
  $CHANGES

# 3) 변경사항이 없을 경우
no-changes-template: '이번 릴리즈에는 변경사항이 없습니다.'

# 4) 자동 제외할 라벨·작성자
exclude:
  labels:
    - '🧪 Tests'         # 테스트 전용 PR 제외
    - '🤖 deploy'        # CI/CD 설정 PR 제외
  authors:
    - dependabot[bot]
    - github-actions[bot]

# 5) 카테고리 정의 (labeler.yml 에 있는 라벨 그대로)
categories:
  - title: '🚀 기능 추가'
    labels:
      - '🚀 Features'

  - title: '🐛 버그 수정'
    labels:
      - '🐛 Bug Fixes'

  - title: '📚 문서'
    labels:
      - '📚 Documentation'

  - title: '🧹 자잘한 작업'
    labels:
      - '🧹 Chores'
