# .github/release-drafter.yml

# 릴리즈 제목 포맷
name-template: '릴리즈 v$NEXT_PATCH_VERSION'

# 태그 포맷
tag-template: 'v$NEXT_PATCH_VERSION'

# Draft Release 본문 템플릿
template: |
  ### 📱 Android 빌드 버전
  <!-- 예) 12345 -->

  ### 🍎 iOS 빌드 버전
  <!-- 예) 67890 -->

  ### 🔄 변경사항
  $CHANGES

# 변경사항이 없을 경우 표시할 문구
no-changes-template: '이번 릴리즈에는 변경사항이 없습니다.'

# 자동 제외할 라벨/작성자
exclude:
  labels:
    - ignore-for-release      # 릴리즈 노트에 포함하고 싶지 않은 PR
  authors:
    - dependabot[bot]         # 봇 계정 제외
    - github-actions[bot]     # 액션 봇 제외

# 카테고리 정의 (레이블 기반 매칭)
categories:
  - title: '🚀 기능'
    labels:
      - '🚀 Features'
  - title: '🐛 버그 수정'
    labels:
      - '🐛 Bug Fixes'
  - title: '📚 문서'
    labels:
      - '📚 Documentation'
  - title: '⚡ 성능 개선'
    labels:
      - '⚡ Performance'
  - title: '🔒 보안'
    labels:
      - '🔒 Security'
  - title: '🧹 자잘한 작업'
    labels:
      - '🧹 Chores'
  - title: '🔀 기타 변경사항'
    labels:
      - '*'   # 위에 매칭되지 않은 모든 PR
