# .github/release.yml

changelog:
  # 제외할 라벨/작성자
  exclude:
    labels:
      - ignore-for-release      # 릴리즈 노트에 포함하고 싶지 않은 PR
    authors:
      - dependabot[bot]         # 봇 계정 제외
      - github-actions[bot]

  # 카테고리 정의 (라벨 기반)
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement

    - title: 🐛 Bug Fixes
      labels:
        - bug

    - title: 📚 Documentation
      labels:
        - docs

    - title: ⚡ Performance
      labels:
        - perf

    - title: 🔒 Security
      labels:
        - security

    - title: 🧹 Chores
      labels:
        - chore

    - title: 🔀 Other Changes
      labels:
        - "*"                   # catch-all: 위 라벨에 매칭되지 않은 PR
