# .github/release.yml
changelog:
  exclude:
    labels:
      - ignore-for-release      # 이 라벨이 붙은 PR은 릴리즈 노트에서 제외
    authors:
      - dependabot[bot]         # 봇 PR 제외
      - github-actions[bot]

  categories:
    - title: '🚀 기능 추가'
      labels:
        - '🚀 Features'

    - title: '🐛 버그 수정'
      labels:
        - '🐛 Bug Fixes'

    - title: '🔥 긴급 수정'
      labels:
        - '🔥 Hotfix'

    - title: '📚 문서'
      labels:
        - '📚 Documentation'

    - title: '🧹 자잘한 작업'
      labels:
        - '🧹 Chores'

    - title: '🧪 테스트'
      labels:
        - '🧪 Tests'

    - title: '🤖 CI/CD·배포 설정'
      labels:
        - '🤖 deploy'

    - title: '🔀 기타 변경사항'
      labels:
        - '🔀 Other Changes'
