name: Generate Release Notes

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create GitHub Release with Notes
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}            # 태그명(vX.Y.Z)을 자동 참조
          release_name: Release ${{ github.ref_name }}
          generate_release_notes: true               # GitHub의 자동 릴리즈 노트 기능 사용
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 퍼미션 설정 필요  

      # 선택: Release Asset 업로드
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/output.zip
          asset_name: output.zip
          asset_content_type: application/zip
